Add Forget Password Feature
Restfulness/Restfulness-core-api pull request #30
Opened 2020-11-16 18:57 UTC by farbodahm

For now, we have endpoint to reset password, necessary definitions and simple 8 digit password mechanism. (Work in progress)

2020-11-21 15:48 UTC, farbodahm commented
So with that, I think I can mark this PR as `Ready for review` :)

@pesarkhobeee Would you mind please review this PR?
Also I added a note about how reset password mechanism works in README, I think that would be good to write it here, too.

- **How does reset password mechanism work?**
  1. Client sends a POST request to `/forget` endpoint, containing `user's username`.
  2. Server sends an 8 digit random created code to user's Email and returns a hash string which contains `User's ID, Valid 8 digit code and expire date`. (We use [ItsDangerous](https://itsdangerous.palletsprojects.com) for creating that hash, so it's safe.)
  3. Client sends a POST request to `/verify` endpoint, containing `user's entered 8 digit code` and `hash that was obtained from previous call`.
  4. Server returns a token for resetting password, **If** user entered the correct 8 digit code.
  5. At last, Client sends a POST request to `/reset` endpoint, containing `Reset password token that is obtained from previous call` and `user's new password`.
  6. For more information, read [this](https://dev.to/theanam/otp-verification-without-any-database-4ja5). (To make long story short, we do this to pick up unnecessary pressure from our server.)

2020-11-24 13:23 UTC, farbodahm commented
In last commit, I added Jinja2 for rendering `reset code` Email page. Now it looks like this:

![restfulness_forget_password_email](https://user-images.githubusercontent.com/13691777/100100029-6fff8480-2e75-11eb-8d16-e83423ca6f26.png)

It's just a template, just let me know if you don't like it :)

2020-11-26 09:30 UTC, farbodahm commented
Now we accept verified Email for our `username` filed in Sign-Up, Also I added `created_date` & `updated_date` for `User` and `Link` models.

![db](https://user-images.githubusercontent.com/13691777/100332895-33ec3100-2fe7-11eb-9388-eb6e6a55c0f8.png)

2020-11-27 06:51 UTC, pesarkhobeee commented
Well done @farbodahm 
This weekend I will review your codes :)

2020-11-28 19:23 UTC, pesarkhobeee requested changes
Thanks @farbodahm 
This PR is perfect and wonderful, well done
Just to make it better I put some comments, please fix them 
Also generally I don't know how we should look at our tests because if they are unit tests they should not related to each others result and they should be isolated but for now we can look at them as a kind of integration test

2020-11-28 19:23 UTC, pesarkhobeee commented on common/ResetPasswordCore.py
> +        hash = Serializer(SECRET_KEY, expires_in=300)
The expiration time should be configurable and also the default value should mentioned in the readme file!

2020-11-28 19:23 UTC, pesarkhobeee commented on common/ResetPasswordCore.py
> +        hash = Serializer(SECRET_KEY, expires_in=300)
Same as above but these two should be different variables

2020-11-28 19:23 UTC, pesarkhobeee commented on common/ResetPasswordCore.py
> +            random.choice(string.digits) for i in range(8)
Did you know instead of for loop you can use:
`random.choices(string.digits, k=length)`

2020-11-28 19:23 UTC, pesarkhobeee commented on common/ResetPasswordCore.py
> +    def __generate_8_digit_code() -> str:
this digit code's long should be configurable and the default value should be written in the readme

2020-11-28 19:23 UTC, pesarkhobeee commented on tests/test_forget_password.py
> +    global RESET_PASSWORD_TOKEN
why this should be here?

2020-11-28 19:23 UTC, pesarkhobeee commented on tests/test_forget_password.py
> +    global RESET_PASSWORD_TOKEN
same as above

2020-11-29 10:18 UTC, farbodahm commented
@pesarkhobeee Thanks for your great review, changes applied.

2020-11-29 17:27 UTC, merged